image: alpine/edge
secrets:
- ad3d604c-f310-4a40-b8de-8531da66e6c7
sources:
- git@git.sr.ht:~dawbs/dawbs.co.uk
oauth: pages.sr.ht/PAGES:RW
packages:
- hut
environment:
  site: dawbs.co.uk
tasks:
- package: |
    cd $site
    cd build
    tar -cvz ./ > ../../site.tar.gz
- upload: |
    hut pages publish -d $site site.tar.gz
