image: alpine/edge
secrets:
- f62ad994-840c-4c8a-b22e-7a877f198766
sources:
- git@git.sr.ht:~dawbs/dawbs.co.uk
oauth: pages.sr.ht/PAGES:RW
packages:
- hut
environment:
  site: dawbs.co.uk
tasks:
- package: |
    cd $site
    cd build
    tar -cvz ./ > ../../site.tar.gz
- upload: |
    hut pages publish -d $site site.tar.gz
